function createData(
  date,
  lastName,
  firstName,
  birthday,
  physician,
  technician,
  headDoctor,
  impression,
  updatedAt,
  clinic,
  user
) {
  return {
    date,
    lastName,
    firstName,
    birthday,
    physician,
    technician,
    headDoctor,
    impression,
    updatedAt,
    clinic,
    user,
  };
}

export const rows = [
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
  createData(
    "9/15/19",
    "John",
    "Doe",
    "2/10/67",
    "John Johnson",
    "John Johnson",
    "John Johnson",
    "NORMAL",
    "10/14/19 22:49",
    "Audiology Center of Maine",
    "John"
  ),
];

export const headCells = [
  {
    id: "date",
    numeric: false,
    disablePadding: false,
    label: "DATE",
  },
  { id: "lastName", numeric: false, disablePadding: false, label: "LAST NAME" },
  {
    id: "firstName",
    numeric: false,
    disablePadding: false,
    label: "FIRST NAME",
  },
  { id: "birthday", numeric: false, disablePadding: false, label: "DOB" },
  {
    id: "physician",
    numeric: false,
    disablePadding: false,
    label: "PHYSICIAN",
  },
  {
    id: "technician",
    numeric: false,
    disablePadding: false,
    label: "TECHNICIAN",
  },
  {
    id: "headDoctor",
    numeric: false,
    disablePadding: false,
    label: "HEAD DOCTOR",
  },
  {
    id: "impression",
    numeric: false,
    disablePadding: false,
    label: "OVERALL IMPRESSION",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "MODIFIED",
  },
  {
    id: "clinic",
    numeric: false,
    disablePadding: false,
    label: "BY CLINIC",
  },
  {
    id: "user",
    numeric: false,
    disablePadding: false,
    label: "BY USER",
  },
  {
    id: "actions",
    numeric: false,
    disablePadding: false,
    label: "ACTIONS",
  },
];

export const providers = ["John Wayne, M.D.", "Adam", "Nick", "Andrey", "Lucy"];
export const technicians = [
  "John Wayne, M.D.",
  "Adam",
  "Nick",
  "Andrey",
  "Lucy",
];
